# Generated by Django 5.1.2 on 2024-11-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('Market', 'Market'), ('Party', 'Party'), ('Common', 'Common')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('price', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
