# Generated by Django 5.1.2 on 2024-11-01 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_common'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=10)),
                ('title_mark', models.ForeignKey(limit_choices_to={'page': 'Market'}, on_delete=django.db.models.deletion.CASCADE, related_name='market_product', to='dashboard.product')),
                ('title_part', models.ForeignKey(limit_choices_to={'page': 'Party'}, on_delete=django.db.models.deletion.CASCADE, related_name='party_product', to='dashboard.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Common',
        ),
    ]
